In [44]:
import pandas as pd
import json
import openpyxl

# 1. Base de dados

## 1.1 Importando e tratando a base de clientes e produtos

In [45]:
# Transformar a base "clientes.json" em um DataFrame do Pandas chamado clientes_df, O ID deve ser o índice do DataFrame

# Lê o arquivo JSON
with open('clientes.json', 'r') as file:
    data = json.load(file)

# Cria o DataFrame a partir dos dados JSON
clientes_df = pd.DataFrame(data)

# Define a coluna 'id' como índice do DataFrame
clientes_df.set_index('id', inplace=True)

# Exibe o DataFrame resultante
display(clientes_df)

,idade,nome,Conta Corrente,Poupanca,LCI,ETF,Fundos de Investimento de Renda Fixa,Credito Imobiliario,VGBL,Consorcio,CDB,Fundos de Investimento de Acoes,LCA,Credito Pessoal,Fundos de Investimento Multimercado,Acoes,Fundo de Capitalizacao,PGBL,FII,Cartao de Credito
id,,,,,,,,,,,,,,,,,,,,
1,44,JoÃ£o Santos,29222,72481,58243.0,1527062.0,798359.0,1280909.0,2102757.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29,Fernanda Souza,47433,35499,284786.0,NaN,NaN,689589.0,780307.0,381479.0,362043.0,317404.0,457403.0,9428.0,964128.0,NaN,NaN,NaN,NaN,NaN
3,66,Roberto Almeida,96919,82444,NaN,NaN,1215453.0,582834.0,224739.0,509304.0,NaN,NaN,NaN,NaN,1364886.0,77604.0,482595.0,NaN,NaN,NaN
4,18,AntÃ´nio Rodrigues,30981,26998,48871.0,NaN,NaN,1334423.0,4276986.0,404236.0,NaN,1472023.0,160576.0,14078.0,389310.0,NaN,398114.0,1208995.0,NaN,NaN
5,37,Thiago Oliveira,50574,75078,NaN,NaN,1561185.0,NaN,NaN,467584.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2888702.0,674631.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,44,Beatriz Dias,22834,97731,NaN,1895537.0,1730776.0,NaN,NaN,905201.0,NaN,NaN,48594.0,5420.0,1418627.0,1465035.0,NaN,3516604.0,1193228.0,5.0
97,67,Juliana Costa,59193,90520,NaN,1576920.0,NaN,144331.0,NaN,NaN,286894.0,NaN,NaN,60725.0,1846020.0,NaN,28888.0,NaN,NaN,NaN
98,27,Juliana Dias,37401,55595,467105.0,NaN,NaN,1860417.0,691243.0,111358.0,48018.0,NaN,NaN,78245.0,1339136.0,NaN,473581.0,NaN,1841728.0,4.0
99,66,Camila Santos,40962,58989,NaN,NaN,NaN,NaN,NaN,692332.0,283136.0,949232.0,NaN,NaN,NaN,63807.0,NaN,NaN,480637.0,NaN
100,31,Fernanda Fernandes,38991,83670,NaN,1424518.0,NaN,2586505.0,2619904.0,404858.0,319286.0,NaN,NaN,NaN,1296271.0,NaN,443266.0,2047215.0,NaN,NaN

## 1.2 Verificandos como está o DataFrame

In [46]:
clientes_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 1 to 100
Data columns (total 20 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   idade                                 100 non-null    int64
 1   nome                                  100 non-null    object
 2   Conta Corrente                        100 non-null    int64
 3   Poupanca                              100 non-null    int64
 4   LCI                                   38 non-null     float64
 5   ETF                                   45 non-null     float64
 6   Fundos de Investimento de Renda Fixa  45 non-null     float64
 7   Credito Imobiliario                   43 non-null     float64
 8   VGBL                                  44 non-null     float64
 9   Consorcio                             56 non-null     float64
 10  CDB                                   43 non-null     float64
 11  Fundos de Investimento de Acoes       41 non-null     float64
 12  LCA                                   53 non-null     float64
 13  Credito Pessoal                       37 non-null     float64
 14  Fundos de Investimento Multimercado   54 non-null     float64
 15  Acoes                                 43 non-null     float64
 16  Fundo de Capitalizacao                51 non-null     float64
 17  PGBL                                  47 non-null     float64
 18  FII                                   34 non-null     float64
 19  Cartao de Credito                     36 non-null     float64
dtypes: float64(16), int64(3), object(1)
memory usage: 16.4+ KB

In [47]:
# Converte as colunas Conta Corrente e Poupança para float
clientes_df['Conta Corrente'] = clientes_df['Conta Corrente'].astype(float)
clientes_df['Poupanca'] = clientes_df['Poupanca'].astype(float)

clientes_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 1 to 100
Data columns (total 20 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   idade                                 100 non-null    int64
 1   nome                                  100 non-null    object
 2   Conta Corrente                        100 non-null    float64
 3   Poupanca                              100 non-null    float64
 4   LCI                                   38 non-null     float64
 5   ETF                                   45 non-null     float64
 6   Fundos de Investimento de Renda Fixa  45 non-null     float64
 7   Credito Imobiliario                   43 non-null     float64
 8   VGBL                                  44 non-null     float64
 9   Consorcio                             56 non-null     float64
 10  CDB                                   43 non-null     float64
 11  Fundos de Investimento de Acoes       41 non-null     float64
 12  LCA                                   53 non-null     float64
 13  Credito Pessoal                       37 non-null     float64
 14  Fundos de Investimento Multimercado   54 non-null     float64
 15  Acoes                                 43 non-null     float64
 16  Fundo de Capitalizacao                51 non-null     float64
 17  PGBL                                  47 non-null     float64
 18  FII                                   34 non-null     float64
 19  Cartao de Credito                     36 non-null     float64
dtypes: float64(18), int64(1), object(1)
memory usage: 16.4+ KB

## 1.3 Substituindo os valores nulos por 0

In [48]:
# Preenche valores ausentes com 0
clientes_df.fillna(0, inplace=True)
clientes_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 1 to 100
Data columns (total 20 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   idade                                 100 non-null    int64
 1   nome                                  100 non-null    object
 2   Conta Corrente                        100 non-null    float64
 3   Poupanca                              100 non-null    float64
 4   LCI                                   100 non-null    float64
 5   ETF                                   100 non-null    float64
 6   Fundos de Investimento de Renda Fixa  100 non-null    float64
 7   Credito Imobiliario                   100 non-null    float64
 8   VGBL                                  100 non-null    float64
 9   Consorcio                             100 non-null    float64
 10  CDB                                   100 non-null    float64
 11  Fundos de Investimento de Acoes       100 non-null    float64
 12  LCA                                   100 non-null    float64
 13  Credito Pessoal                       100 non-null    float64
 14  Fundos de Investimento Multimercado   100 non-null    float64
 15  Acoes                                 100 non-null    float64
 16  Fundo de Capitalizacao                100 non-null    float64
 17  PGBL                                  100 non-null    float64
 18  FII                                   100 non-null    float64
 19  Cartao de Credito                     100 non-null    float64
dtypes: float64(18), int64(1), object(1)
memory usage: 16.4+ KB

# 2. Recomendação de produtos

## 2.1 Calculando distancia euclidiana entre os clientes

In [49]:
# Verifica a semelhança entre os clientes com base na Conta Corrente, poupança e idade (Vetor 3D)
# Calcula a distancia euclidiana entre os clientes e cria uma coluna no final do dataframe informando o ID do cliente mais próximo
# Utiliza a diferença entre as idades e o saldo da conta corrente e poupança para calcular a distância euclidiana


def euclidean_distance(row1, row2):
    # Diferença ao quadrado entre as idades, Conta Corrente e Poupança
    age_diff = (row1['idade'] - row2['idade']) ** 2
    cc_diff = (row1['Conta Corrente'] - row2['Conta Corrente']) ** 2
    cp_diff = (row1['Poupanca'] - row2['Poupanca']) ** 2
    return (age_diff + cc_diff + cp_diff) ** 0.5

# Cria uma coluna para armazenar o ID do cliente mais próximo
clientes_df['id_cliente_mais_proximo'] = None

# Calcula a distância euclidiana entre cada cliente e todos os outros clientes
for index, row in clientes_df.iterrows():
    distances = []
    for index2, row2 in clientes_df.iterrows():
        if index != index2:  # Não comparar o cliente consigo mesmo
            dist = euclidean_distance(row, row2)
            distances.append((index2, dist))
    
    # Encontra o ID do cliente mais próximo
    closest_client = min(distances, key=lambda x: x[1])
    clientes_df.at[index, 'id_cliente_mais_proximo'] = closest_client[0]

# Exibe o DataFrame atualizado com a coluna do cliente mais próximo
display(clientes_df.head(5))

,idade,nome,Conta Corrente,Poupanca,LCI,ETF,Fundos de Investimento de Renda Fixa,Credito Imobiliario,VGBL,Consorcio,...,Fundos de Investimento de Acoes,LCA,Credito Pessoal,Fundos de Investimento Multimercado,Acoes,Fundo de Capitalizacao,PGBL,FII,Cartao de Credito,id_cliente_mais_proximo
id,,,,,,,,,,,,,,,,,,,,,
1,44,JoÃ£o Santos,29222.0,72481.0,58243.0,1527062.0,798359.0,1280909.0,2102757.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10
2,29,Fernanda Souza,47433.0,35499.0,284786.0,0.0,0.0,689589.0,780307.0,381479.0,...,317404.0,457403.0,9428.0,964128.0,0.0,0.0,0.0,0.0,0.0,37
3,66,Roberto Almeida,96919.0,82444.0,0.0,0.0,1215453.0,582834.0,224739.0,509304.0,...,0.0,0.0,0.0,1364886.0,77604.0,482595.0,0.0,0.0,0.0,39
4,18,AntÃ´nio Rodrigues,30981.0,26998.0,48871.0,0.0,0.0,1334423.0,4276986.0,404236.0,...,1472023.0,160576.0,14078.0,389310.0,0.0,398114.0,1208995.0,0.0,0.0,75
5,37,Thiago Oliveira,50574.0,75078.0,0.0,0.0,1561185.0,0.0,0.0,467584.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2888702.0,674631.0,0.0,78

## 2.2 Criar coluna com lista dos serviços contratados por cada cliente

In [50]:
# Cria uma nova nova coluna com a lista de produtos contratados por cada cliente, a partir das colunas: Conta Corrente, 
# Poupanca, Credito Imobiliario, Fundos de Investimento de Acoes, Cartao de Credito, PGBL, ETF, LCI, 
# Fundos de Investimento Multimercado, Consorcio, Fundo de Capitalizacao, LCA, Fundos de Investimento de Renda Fixa, 
# VGBL, Credito Pessoal, FII, CDB, Acoes. Quando o valor for maior que 0, o produtos deve ser adicionado à lista, 
# caso contrário não deve ser adicionado.   

def get_services(row):
    services = []
    if row['Conta Corrente'] > 0:
        services.append('Conta Corrente')
    if row['Poupanca'] > 0:
        services.append('Poupanca')
    if row['Credito Imobiliario'] > 0:
        services.append('Credito Imobiliario')
    if row['Fundos de Investimento de Acoes'] > 0:
        services.append('Fundos de Investimento de Acoes')
    if row['Cartao de Credito'] > 0:
        services.append('Cartao de Credito')
    if row['PGBL'] > 0:
        services.append('PGBL')
    if row['ETF'] > 0:
        services.append('ETF')
    if row['LCI'] > 0:
        services.append('LCI')
    if row['Fundos de Investimento Multimercado'] > 0:
        services.append('Fundos de Investimento Multimercado')
    if row['Consorcio'] > 0:
        services.append('Consorcio')
    if row['Fundo de Capitalizacao'] > 0:
        services.append('Fundo de Capitalizacao')
    if row['LCA'] > 0:
        services.append('LCA')
    if row['Fundos de Investimento de Renda Fixa'] > 0:
        services.append('Fundos de Investimento de Renda Fixa')
    if row['VGBL'] > 0:
        services.append('VGBL')
    if row['Credito Pessoal'] > 0:
        services.append('Credito Pessoal')
    if row['FII'] > 0:
        services.append('FII')
    if row['CDB'] > 0:
        services.append('CDB')
    if row['Acoes'] > 0:
        services.append('Acoes')

    return ', '.join(services)

# Aplica a função para criar a nova coluna de serviços
clientes_df['produtos_contratados'] = clientes_df.apply(get_services, axis=1)

# Exibe o DataFrame atualizado com a nova coluna de serviços contratados
display(clientes_df.head(5))

,idade,nome,Conta Corrente,Poupanca,LCI,ETF,Fundos de Investimento de Renda Fixa,Credito Imobiliario,VGBL,Consorcio,...,LCA,Credito Pessoal,Fundos de Investimento Multimercado,Acoes,Fundo de Capitalizacao,PGBL,FII,Cartao de Credito,id_cliente_mais_proximo,produtos_contratados
id,,,,,,,,,,,,,,,,,,,,,
1,44,JoÃ£o Santos,29222.0,72481.0,58243.0,1527062.0,798359.0,1280909.0,2102757.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,"Conta Corrente, Poupanca, Credito Imobiliario,..."
2,29,Fernanda Souza,47433.0,35499.0,284786.0,0.0,0.0,689589.0,780307.0,381479.0,...,457403.0,9428.0,964128.0,0.0,0.0,0.0,0.0,0.0,37,"Conta Corrente, Poupanca, Credito Imobiliario,..."
3,66,Roberto Almeida,96919.0,82444.0,0.0,0.0,1215453.0,582834.0,224739.0,509304.0,...,0.0,0.0,1364886.0,77604.0,482595.0,0.0,0.0,0.0,39,"Conta Corrente, Poupanca, Credito Imobiliario,..."
4,18,AntÃ´nio Rodrigues,30981.0,26998.0,48871.0,0.0,0.0,1334423.0,4276986.0,404236.0,...,160576.0,14078.0,389310.0,0.0,398114.0,1208995.0,0.0,0.0,75,"Conta Corrente, Poupanca, Credito Imobiliario,..."
5,37,Thiago Oliveira,50574.0,75078.0,0.0,0.0,1561185.0,0.0,0.0,467584.0,...,0.0,0.0,0.0,0.0,0.0,2888702.0,674631.0,0.0,78,"Conta Corrente, Poupanca, PGBL, Consorcio, Fun..."

## 2.3 Recomendando produtos financeiros para os clientes

In [51]:
# Cria uma nova coluna chamada produtos recomendados, que contem os produtos recomendados para cada cliente, 
# com base nos produtos contratados e os produtos do cliente mais próximo (Diferença).

def recommend_products(row):
    recommended_products = set()
    actual_products = set()
    
    # Produtos contratados pelo cliente
    if row['produtos_contratados']:
        actual_products = row['produtos_contratados'].split(', ')
    
    # Adiciona os produtos do cliente mais próximo
    closest_client_id = row['id_cliente_mais_proximo']

    if closest_client_id in clientes_df.index:
        closest_client_products = clientes_df.at[closest_client_id, 'produtos_contratados'].split(', ')

        if closest_client_products:
            # Recomenda os produtos do cliente mais próximo que o cliente atual não possui
            for product in closest_client_products:
               if product not in actual_products:
                    recommended_products.add(product.strip())

    return ', '.join(recommended_products)

# Aplica a função para criar a nova coluna de produtos recomendados
clientes_df['produtos_recomendados'] = clientes_df.apply(recommend_products, axis=1)

# Exibe o DataFrame atualizado com a nova coluna de produtos recomendados
display(clientes_df.head(5))

# Salvar o DataFrame atualizado em um arquivo Excel chamado "clientes.xlsx"
clientes_df.to_excel('Produtos_Recomendados.xlsx', engine='openpyxl')

,idade,nome,Conta Corrente,Poupanca,LCI,ETF,Fundos de Investimento de Renda Fixa,Credito Imobiliario,VGBL,Consorcio,...,Credito Pessoal,Fundos de Investimento Multimercado,Acoes,Fundo de Capitalizacao,PGBL,FII,Cartao de Credito,id_cliente_mais_proximo,produtos_contratados,produtos_recomendados
id,,,,,,,,,,,,,,,,,,,,,
1,44,JoÃ£o Santos,29222.0,72481.0,58243.0,1527062.0,798359.0,1280909.0,2102757.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,"Conta Corrente, Poupanca, Credito Imobiliario,...","Fundos de Investimento Multimercado, LCA, Acoe..."
2,29,Fernanda Souza,47433.0,35499.0,284786.0,0.0,0.0,689589.0,780307.0,381479.0,...,9428.0,964128.0,0.0,0.0,0.0,0.0,0.0,37,"Conta Corrente, Poupanca, Credito Imobiliario,...","FII, Fundo de Capitalizacao, Cartao de Credito..."
3,66,Roberto Almeida,96919.0,82444.0,0.0,0.0,1215453.0,582834.0,224739.0,509304.0,...,0.0,1364886.0,77604.0,482595.0,0.0,0.0,0.0,39,"Conta Corrente, Poupanca, Credito Imobiliario,...",
4,18,AntÃ´nio Rodrigues,30981.0,26998.0,48871.0,0.0,0.0,1334423.0,4276986.0,404236.0,...,14078.0,389310.0,0.0,398114.0,1208995.0,0.0,0.0,75,"Conta Corrente, Poupanca, Credito Imobiliario,...","FII, Cartao de Credito, Acoes"
5,37,Thiago Oliveira,50574.0,75078.0,0.0,0.0,1561185.0,0.0,0.0,467584.0,...,0.0,0.0,0.0,0.0,2888702.0,674631.0,0.0,78,"Conta Corrente, Poupanca, PGBL, Consorcio, Fun...","Fundos de Investimento Multimercado, LCA, VGBL..."

## 2.4 Base: Recomendação de Produtos

In [52]:
# Dataframe com o nome do cliente e os produtos atuais e recomendados
resumo_recomendacao = clientes_df[['nome', 'produtos_contratados', 'produtos_recomendados']]
display(resumo_recomendacao)

# Salvar o DataFrame atualizado em um arquivo Excel
resumo_recomendacao .to_excel('Produtos_Recomendados_Resumido.xlsx', engine='openpyxl')

,nome,produtos_contratados,produtos_recomendados
id,,,
1,JoÃ£o Santos,"Conta Corrente, Poupanca, Credito Imobiliario,...","Fundos de Investimento Multimercado, LCA, Acoe..."
2,Fernanda Souza,"Conta Corrente, Poupanca, Credito Imobiliario,...","FII, Fundo de Capitalizacao, Cartao de Credito..."
3,Roberto Almeida,"Conta Corrente, Poupanca, Credito Imobiliario,...",
4,AntÃ´nio Rodrigues,"Conta Corrente, Poupanca, Credito Imobiliario,...","FII, Cartao de Credito, Acoes"
5,Thiago Oliveira,"Conta Corrente, Poupanca, PGBL, Consorcio, Fun...","Fundos de Investimento Multimercado, LCA, VGBL..."
...,...,...,...
96,Beatriz Dias,"Conta Corrente, Poupanca, Cartao de Credito, P...","LCI, Fundos de Investimento de Acoes, Fundo de..."
97,Juliana Costa,"Conta Corrente, Poupanca, Credito Imobiliario,...","Fundos de Investimento de Acoes, PGBL, LCA, FI..."
98,Juliana Dias,"Conta Corrente, Poupanca, Credito Imobiliario,...","PGBL, Fundos de Investimento de Acoes, Fundos ..."
99,Camila Santos,"Conta Corrente, Poupanca, Fundos de Investimen...","Fundos de Investimento Multimercado, Credito P..."
100,Fernanda Fernandes,"Conta Corrente, Poupanca, Credito Imobiliario,...","FII, LCA, Acoes, Fundos de Investimento de Ren..."